### PR TITLE
Dev code chunks

### PR DESCRIPTION
**Pull request by abhsarma**
Its not passing all the checks because of one warnings and a couple notes but these are because of importing unexported functions from knitr (which has dependencies on other packages). It should get fixed by submitting a pull request to knitr, so not sure if its worth spending time fixing that

### CODE REVIEW

**Comment by mjskay** [comment]
Understood re: the warning. I think it might be good to figure out a way to fix it even for the hot-patching. It seems you can get around using `:::` and avoid the warning. I can take a look at that.

You should address the NOTEs you have remaining though as they are all straightforward to address and fixing them will make the CHECK output a lot easier to read (especially if you still have a WARNING to ignore / read around). 

Looks like you have some missing imports and some missing globalVariables definitions:

```
   Undefined global functions or variables:
    !<- %n% . .parameter_assignment .universe cache cache_output_name
    comment_out copy_env dep_list dev.control dev.cur dev.list dev.new
    dev.off find_globals fix_evaluate get_engine head line_prompt
    merge_low_plot na.omit one_string par par2 parse_chunk parse_only
    remove_plot sc_split sym<- tail tikz_dev try_silent valid_path
  Consider adding
    importFrom("grDevices", "dev.control", "dev.cur", "dev.list",
               "dev.new", "dev.off")
    importFrom("graphics", "par")
    importFrom("stats", "na.omit")
    importFrom("utils", "head", "tail")
```

For the global variables problem see here: https://github.com/STAT545-UBC/Discussion/issues/451 (you can see some examples of usage of this in tidybayes)

For the LICENSE NOTE I think you need to add LICENSE to your `.Rbuildignore` file

**Comment by abhsarma** [comment]
Okay I'll address the other stuff. I think some of them could just be fixed by removing the functions related to overriding the `$` operator that we used to have.
For the LICENSE, adding it to .Rbuildignore instead gives me a warning: 
`checking` DESCRIPTION meta-information ... WARNING
  Invalid license file pointers: LICENSE`

**Comment by abhsarma** [comment]
ah never mind, figured out the LICENSE file problem. I was linking to it in the description, which I should not have

**Comment by mjskay** [comment]
Cool sounds good. Might be good to do a pass through the issues and close any that have been fixed / are no longer relevant too.

**Pull request closed without merging**
